on:
  issue_comment:
    types: [created]

jobs:
  pr_merge:
    # This job only runs for pull request comments
    name: PR Merge
    if: |
      github.event.issue.pull_request && github.event.comment.body == '/merge' && github.event.comment.user.login == 'brianseeders'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Squash commits
        run: |
          set -euxo pipefail
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          gh pr checkout "$PR_NUMBER"
          SHA=$(git rev-parse HEAD)
          git checkout main
          git checkout -b staging-$PR_NUMBER
          git rev-parse HEAD
          git status
          git merge --allow-unrelated-histories --squash $SHA 
          git commit -m "$PR_TITLE #$PR_NUMBER"
          gh pr checkout "$PR_NUMBER"
          git reset --hard staging-$PR_NUMBER
          git push -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ github.event.issue.user.login }}
          GIT_AUTHOR_EMAIL: ${{ github.event.issue.user.id }}+${{ github.event.issue.user.login }}@users.noreply.github.com
          PR_NUMBER: ${{ github.event.issue.number }}
          PR_TITLE: ${{ github.event.issue.title }}
