on:
  issue_comment:
    types: [created]

jobs:
  pr_merge:
    # This job only runs for pull request comments
    name: PR Merge
    if: |
      github.event.issue.pull_request && github.event.comment.body == '/merge' && github.event.comment.user.login == 'brianseeders'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Squash commits
        run: |
          git reset --hard main
          git checkout ${{ github.event.issue.pull_request.head.sha }} .
          git push -f
