on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  ci:
    name: PR CI
    if: |
      github.event.sender.login != 'TODO'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          name: 'bors-testing'
      - run: ./pipeline.sh
      - if: always()
        uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          name: 'bors-testing'
          status: '${{ job.status }}'
